# Generated by Django 2.1.5 on 2021-11-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herbalist',
            fields=[
                ('HerbalistId', models.IntegerField(primary_key=True, serialize=False)),
                ('HerbalistFname', models.CharField(max_length=30)),
                ('HerbalistLname', models.CharField(max_length=30)),
                ('HerbalistUsername', models.CharField(max_length=20)),
                ('herbalistEmail', models.EmailField(max_length=254)),
                ('HerbalistContact', models.IntegerField(max_length=15)),
                ('HerbalistSpecialization', models.CharField(max_length=255)),
            ],
        ),
    ]
