# Generated by Django 2.1.5 on 2021-11-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211121_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herbalist',
            old_name='HerbalistFname',
            new_name='FirstName',
        ),
        migrations.AlterField(
            model_name='herbalist',
            name='HerbalistContact',
            field=models.CharField(max_length=15),
        ),
    ]
