# Generated by Django 2.1.5 on 2021-11-22 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_auto_20211121_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='HerbalistID',
        ),
    ]
