# Generated by Django 2.1.5 on 2021-11-22 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_post_user'),
    ]
