# Generated by Django 2.1.5 on 2021-11-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211122_0509'),
    ]

