# Generated by Django 2.1.5 on 2021-11-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiseaseName', models.CharField(max_length=50)),
                ('DiseaseDescription', models.TextField()),
                ('DiseasePhoto', models.ImageField(default='default.jpeg', upload_to='diseasePhotos')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusId', models.CharField(max_length=5)),
                ('statusDescription', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='DiseaseStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.DiseaseStatus'),
        ),
    ]
