# Generated by Django 2.1.5 on 2021-11-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20211124_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='DiseaseStatus',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='diseasestatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='diseasestatus',
            name='statusId',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
