# Generated by Django 2.1.5 on 2021-11-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20211124_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasestatus',
            name='statusId',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
