# Generated by Django 2.1.5 on 2021-11-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20211128_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('statusId', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('statusType', models.CharField(max_length=20)),
            ],
        ),
    ]
