# Generated by Django 2.1.5 on 2021-11-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='statusType',
            field=models.CharField(max_length=100),
        ),
    ]
