# Generated by Django 2.1.5 on 2021-12-01 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20211130_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
