# Generated by Django 2.1.5 on 2021-12-02 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_disease_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
